.PHONY: check lint format all

# Используем python -m ruff вместо просто ruff
PYTHON = python
RUFF = $(PYTHON) -m ruff

check:

	$(RUFF) check .

lint:

	$(RUFF) check --fix .

format:

	$(RUFF) format .
all: format lint 